services:
  - type: web
    name: fashion-community-backend
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000